spring.application.name=boat_reservation
spring.datasource.url=jdbc:mysql://localhost:3306/boatReservation?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true